# .github/workflows/test.yml
name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Unit Tests
      run: go test -v ./...

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y v4l2loopback-dkms v4l-utils ffmpeg

    - name: Run Integration Tests
      run: |
        export CI=true
        # TestMain will handle v4l2loopback setup automatically
        sudo go test -v -tags=integration ./test/...
